# Test corpus for tomlq. Each case: (name, toml_text, keypath|None, expect, visible)
# expect: "ok" (compare to tomllib), "parse_error" (exit 1), "missing_key" (exit 2)
CASES = [
 # ---- basics ----
 ("empty_doc", "", None, "ok", True),
 ("comments_only", "# just a comment\n\n   # another\n", None, "ok", True),
 ("simple_kv", 'title = "TOML"\nn = 42\nf = 3.5\nb = true\nc = false\n', None, "ok", True),
 ("bare_keys", 'key-1 = 1\n_x = 2\n1234 = "num key"\nCamelCase = 3\n', None, "ok", True),
 ("quoted_keys", '"my key" = 1\n\'lit key\' = 2\n"" = "empty"\n"ʎǝʞ" = "uni"\n', None, "ok", False),
 ("dotted_keys", 'a.b.c = 1\na . d = 2\nx."y.z".w = 3\nsite."google.com" = true\n', None, "ok", True),
 ("numeric_looking_keys", 'true = 1\n3.14159 = "pi"\n', None, "ok", False),
 ("tabs_and_spaces", 'key\t=\t"v"\n  indented   =   1  \n', None, "ok", True),
 ("hash_in_string", 's = "a # not a comment" # real comment\nt = \'#\'\n', None, "ok", True),
 # ---- strings ----
 ("escapes", 's = "tab\\there\\nnew \\"q\\" back\\\\slash \\u00e9 \\U0001F600 \\b\\f\\r"\n', None, "ok", True),
 ("literal_string", "p = 'C:\\Users\\x'\nre = '<\\i\\c*\\s*>'\n", None, "ok", True),
 ("unicode_raw", 's = "héllo wörld ✓ 日本"\n', None, "ok", False),
 ("ml_basic_trim", 's = """\nRoses are red\nViolets are blue"""\n', None, "ok", True),
 ("ml_basic_backslash", 's = """\nThe quick brown \\\n\n  fox jumps over \\\n    the lazy dog."""\nt = """\\\n  trimmed  \\\n  """\n', None, "ok", True),
 ("ml_basic_quotes", 's = """Here are two quotation marks: "". Simple enough."""\nq = """say "hi" now"""\nr = """Here are three quotation marks: ""\\"."""\n', None, "ok", False),
 ("ml_literal", "s = '''\nraw \\n text\n'''\nre = '''I [dw]on't need \\d{2} apples'''\nq = '''Here are fifteen quotation marks: \"\"\"\"\"\"\"\"\"\"\"\"\"\"\"'''\n", None, "ok", True),
 ("ml_with_escapes", 's = """line1\\n\\tline2 \\u0041"""\n', None, "ok", False),
 # ---- numbers ----
 ("integers", 'a = +99\nb = 42\nc = 0\nd = -17\ne = 1_000\nf = 5_349_221\ng = -0\nh = +0\nbig = 9223372036854775807\n', None, "ok", True),
 ("int_bases", 'hex1 = 0xDEADBEEF\nhex2 = 0xdead_beef\noct1 = 0o01234567\noct2 = 0o755\nbin1 = 0b11010110\n', None, "ok", True),
 ("floats", 'a = +1.0\nb = 3.1415\nc = -0.01\nd = 5e+22\ne = 1e06\nf = -2E-2\ng = 6.626e-34\nh = 224_617.445_991_228\ni = 0.0\nj = -0.0\n', None, "ok", True),
 ("int_vs_float", 'i = 1\nf = 1.0\ne = 1e0\n', None, "ok", True),
 # ---- arrays ----
 ("arrays", 'ints = [ 1, 2, 3 ]\nstrs = [ "red", "yellow", "green" ]\nnested = [ [ 1, 2 ], [3, 4, 5] ]\nmixed = [ 1, "two", 3.0, true, [4] ]\nempty = []\n', None, "ok", True),
 ("array_multiline", 'a = [\n  1,\n  2, # comment\n\n  3,\n]\nb = [ "a,b", "]c[", # tricky\n  \'d\' ]\n', None, "ok", True),
 ("array_of_inline_tables", 'points = [ { x = 1, y = 2, z = 3 },\n           { x = 7, y = 8, z = 9 },\n           { x = 2, y = 4, z = 8 } ]\n', None, "ok", True),
 ("nested_arrays_strings", 'x = [[["deep"]], []]\ny = [ [ "a", "b" ], [ 1, 2 ] ]\n', None, "ok", False),
 # ---- inline tables ----
 ("inline_tables", 'name = { first = "Tom", last = "Preston-Werner" }\npoint = { x = 1, y = 2 }\nanimal = { type.name = "pug" }\nempty = {}\nnest = { a = { b = { c = [1, {d = 2}] } } }\n', None, "ok", True),
 # ---- tables ----
 ("tables", '[table-1]\nkey1 = "some string"\nkey2 = 123\n\n[table-2]\nkey1 = "another string"\nkey2 = 456\n', None, "ok", True),
 ("table_quoted_and_dotted", '[dog."tater.man"]\ntype.name = "pug"\n\n[ a . b . c ]\nq = 1\n\n[ "quoted key with spaces" ]\nz = 2\n', None, "ok", True),
 ("implicit_and_super_after_sub", '[x.y.z.w]\nv = 1\n\n[x.y]\nq = 2\n\n[x]\nz = 3\n', None, "ok", True),
 ("dotted_then_subtable_header", '[fruit]\napple.color = "red"\napple.taste.sweet = true\n\n[fruit.apple.texture]\nsmooth = true\n', None, "ok", False),
 ("deep_nesting", '[a.b.c.d.e]\nf = 1\n[a.b.c]\ng = 2\n[a]\nh = 3\n', None, "ok", False),
 ("dotted_inside_table", '[owner]\nname.first = "a"\nname.last = "b"\nage = 3\n[owner.address]\ncity = "x"\n', None, "ok", True),
 # ---- arrays of tables ----
 ("array_of_tables", '[[products]]\nname = "Hammer"\nsku = 738594937\n\n[[products]]  # empty table within the array\n\n[[products]]\nname = "Nail"\nsku = 284758393\ncolor = "gray"\n', None, "ok", True),
 ("nested_array_of_tables", '[[fruits]]\nname = "apple"\n\n[fruits.physical]\ncolor = "red"\nshape = "round"\n\n[[fruits.varieties]]\nname = "red delicious"\n\n[[fruits.varieties]]\nname = "granny smith"\n\n[[fruits]]\nname = "banana"\n\n[[fruits.varieties]]\nname = "plantain"\n', None, "ok", True),
 ("aot_last_element", '[[a]]\nx = 1\n[a.b]\ny = 1\n[[a]]\nx = 2\n[a.b]\ny = 2\n', None, "ok", False),
 ("aot_empty_only", '[[x]]\n', None, "ok", False),
 # ---- keypath ----
 ("kp_array", '[server]\nports = [ 8000, 8001, 8002 ]\nenabled = true\n', "server.ports", "ok", True),
 ("kp_string", '[owner]\nname = "Tom"\n', "owner.name", "ok", True),
 ("kp_aot", '[[products]]\nname = "Hammer"\n[[products]]\nname = "Nail"\n', "products", "ok", True),
 ("kp_inline", 'p = { x = { y = 5 } }\n', "p.x.y", "ok", False),
 ("kp_top_int", 'n = 7\n', "n", "ok", False),
 ("kp_bool", 'flags = { on = false }\n', "flags.on", "ok", False),
 ("kp_missing", '[server]\nports = [1]\n', "server.host", "missing_key", True),
 ("kp_missing_through_value", 'a = 1\n', "a.b", "missing_key", False),
 ("kp_missing_top", 'a = 1\n', "zzz", "missing_key", False),
 # ---- parse errors ----
 ("dup_key", 'a = 1\na = 2\n', None, "parse_error", True),
 ("dup_table", '[a]\nx = 1\n[a]\ny = 2\n', None, "parse_error", True),
 ("value_then_table", '[a]\nb = 1\n[a.b]\nc = 2\n', None, "parse_error", True),
 ("static_array_then_aot", 'x = [1, 2]\n[[x]]\ny = 1\n', None, "parse_error", False),
 ("aot_then_table", '[[a]]\nx = 1\n[a]\ny = 2\n', None, "parse_error", False),
 ("inline_table_extended", 't = { a = 1 }\nt.b = 2\n', None, "parse_error", True),
 ("inline_table_then_header", 't = { a = 1 }\n[t.c]\nd = 1\n', None, "parse_error", False),
 ("leading_zero", 'n = 007\n', None, "parse_error", True),
 ("unterminated_string", 's = "abc\n', None, "parse_error", True),
 ("missing_value", 'key =\n', None, "parse_error", True),
 ("no_key", '= 1\n', None, "parse_error", False),
 ("bare_key_space", 'my key = 1\n', None, "parse_error", True),
 ("two_pairs_one_line", 'a = 1 b = 2\n', None, "parse_error", True),
 ("inline_trailing_comma", 't = { a = 1, }\n', None, "parse_error", False),
 ("bad_escape", 's = "\\q"\n', None, "parse_error", True),
 ("unterminated_array", 'arr = [1, 2\n', None, "parse_error", False),
 ("bad_literal", 'x = tru\n', None, "parse_error", True),
 ("newline_in_basic_string", 's = "abc\ndef"\n', None, "parse_error", False),
 ("dotted_redefines_value", 'a = 1\na.b = 2\n', None, "parse_error", False),
 ("table_then_dotted_conflict", '[a.b]\nc = 1\n[a]\nb = 2\n', None, "parse_error", False),
 ("array_missing_comma", 'a = [1 2]\n', None, "parse_error", False),
 ("bad_hex", 'h = 0xZZ\n', None, "parse_error", False),
 ("underscore_edge", 'n = 1__0\n', None, "parse_error", False),
 ("junk_after_value", 'a = 1 junk\n', None, "parse_error", False),
 ("junk_after_header", '[a] junk\nb = 1\n', None, "parse_error", False),
]
